Fix cobalt_should_drop() and reduce memory reallocations
dtaht/sch_cake pull request #136
Opened 2020-06-10 15:23 UTC by inste

2020-06-10 17:28 UTC, tohojo commented
For the first commit, I think the proper fix would be to fix the setter in the upstream kernel (and in this repo, wrap it in compat).

Why is the second change needed?

2020-06-10 20:53 UTC, inste commented
> Why is the second change needed?

I've made some measurements of ipv4 forward+napt on mips router with 580 MHz single-core CPU, so every instruction is important there. It appears that on kernel 4.9 skb_try_make_writable() reallocates skb, if skb was allocated in ethernet driver via so-called 'build skb' method from page cache (it was discovered by strange increase of kmalloc-2048 slab at first). This behaviour greatly increase CPU load and decrease throughput (at least by one-third).

2020-06-10 21:07 UTC, tohojo commented
Ilya <notifications@github.com> writes:

>> Why is the second change needed?
>
> I've made some measurements of ipv4 forward+napt on mips router with
> 580 MHz single-core CPU, so every instruction is important there. It
> appears that on kernel 4.9 skb_try_make_writable() reallocates skb, if
> skb was allocated in ethernet driver via so-called 'build skb' method
> from page cache (it was discovered by strange increase of kmalloc-2048
> slab at first). This behaviour greatly increase CPU load and decrease
> throughput (at least by one-third).

Right, that's a useful data point! And reasonable change in that case.
Please put this rationale into the commit message as well...

2020-06-11 06:59 UTC, inste commented
> For the first commit, I think the proper fix would be to fix the setter in the upstream kernel (and in this repo, wrap it in compat).

Yes, upstream can be fixed also, but there are some corner cases:
 - upstream function can't work with fragmented skb, so we must linearize it at first. It it the second place in cake where skb must be linearized (after dscp bleaching in cake_handle_diffserv()).
 - there is no cake_skb_proto() functional in uptsream, so it should be merged first.

As for me, cobalt_set_ce() is specific enough to cake to leave it here.

2020-06-11 10:06 UTC, tohojo commented
> > For the first commit, I think the proper fix would be to fix the setter in the upstream kernel (and in this repo, wrap it in compat).
> 
> Yes, upstream can be fixed also, but there are some corner cases:
> 
>     * upstream function can't work with fragmented skb, so we must linearize it at first. It it the second place in cake where skb must be linearized (after dscp bleaching in cake_handle_diffserv()).
> 
>     * there is no cake_skb_proto() functional in uptsream, so it should be merged first.
> 
> 
> As for me, cobalt_set_ce() is specific enough to cake to leave it here.

Hmm, okay, looking at it again that's a fair point actually :)

2020-06-11 10:23 UTC, tohojo requested changes
A few comments on the diffserv extraction. Also, please add the rationale to the commit message and properly rebase your PR so there are no merge commits.

2020-06-11 10:23 UTC, tohojo commented on sch_cake.c
> +		iph = skb_header_pointer(skb, wlen, sizeof(buf), &buf);
This creates a 'struct iphdr' pointer that points to a data area that is too small, but the fact that it is can be easy to miss. So I'd prefer if you not do that. Instead, use a pointer of a different type to store the return value from skb_header_pointer (say, use a __be16 value for buf, and a pointer of the same type), and then use an explicit cast and a comment when passing it to ipv{4,6}_get_dsfield(). That way it's obvious that something strange is going on, and no one is likely to, say, wonder why the 'iph' pointer is not just reused in the call to ipv{4,6}_change_dsfield() later :)

2020-06-11 10:23 UTC, tohojo commented on sch_cake.c
>  	int wlen = skb_network_offset(skb);
Since you're now using this as an offset rather than a length, I think it's better to rename it...

2020-06-11 10:23 UTC, tohojo commented on sch_cake.c
> +			wlen += sizeof(struct iphdr);
...and then (with the rename above) redefine this as a scope-local variable computed from offset+sizeof()

2020-06-11 10:23 UTC, tohojo commented on sch_cake.c
> +			wlen += sizeof(struct ipv6hdr);
Here as well

2020-06-11 10:23 UTC, tohojo commented on sch_cake.c
> +		ip6h = skb_header_pointer(skb, wlen, sizeof(buf), &buf);
Same comment as above with pointer type

2020-06-23 12:18 UTC, tohojo commented
Ping @inste  - did you have a chance to look at updating this? :)

2020-06-23 12:46 UTC, inste commented
@tohojo sorry for delay, I've realized that 'bus factor' is not only joke... Will rework and test today.

2020-06-23 12:50 UTC, tohojo commented
Ilya <notifications@github.com> writes:

> @tohojo sorry for delay, I've realized that 'bus factor' is not only
> joke...

Yeah, please don't get hit by a bus! ;)

> Will rework and test today.

Great!

2020-06-23 13:14 UTC, inste commented
@tohojo done, but get confused with endless rebasing. Is everything's ok now?

2020-06-23 13:36 UTC, tohojo commented
Nah, the history is even worse now ;)
Ideally this PR should only show the two new commits. I can fix that when merging, though... 

However, I would like it if you could put a bit more of your performance rationale into the second commit message. Specifically, above you said this:

> I've made some measurements of ipv4 forward+napt on mips router with
 580 MHz single-core CPU, so every instruction is important there. It
 appears that on kernel 4.9 skb_try_make_writable() reallocates skb, if
 skb was allocated in ethernet driver via so-called 'build skb' method
 from page cache (it was discovered by strange increase of kmalloc-2048
 slab at first). This behaviour greatly increase CPU load and decrease
 throughput (at least by one-third).

Please put that into the commit message as well; if you have actual before/after numbers that would be even better!

2020-06-23 17:20 UTC, inste commented
@tohojo opened https://github.com/dtaht/sch_cake/pull/137 for proper history.

2020-06-24 13:04 UTC, closed without merging